#!/usr/bin/env python3.5

import discord
import argparse
import sys
from os import environ

parser = argparse.ArgumentParser()
parser.add_argument('token', help='Your token to use')
parser.add_argument('server', help='Server to rip links from')
parser.add_argument('channel', help='Channel to rip links from')
parser.add_argument('limit', help='Number of messages to parse')
parser.add_argument('logfile', help='File name to log to')
args = parser.parse_args()

client = discord.Client()

@client.event
async def on_ready():
    for server in client.servers:
        if server.name == args.server:
            for chan in server.channels:
                if chan.name == args.channel:                    
                    async for message in client.logs_from(chan, limit=int(args.limit)):
                        if 'youtube.' in message.content:
                            with open(environ['HOME'] + '/' + args.logfile + '.html', 'a') as linkListFile:
                                text = message.content
                                if not text.startswith('http'):
                                    text = text[text.index('http'):]
                                if ' ' in text:
                                    text = text[:text.index(' ')]
                                linkListFile.write('<a href="' + text + '">'+ text + '</a> <br><br>\n')
                                print(text)
                    client.close()
                    sys.exit(0)

if __name__ == '__main__':
    client.run(args.token, bot=False)
